name: flutter_html
description: A Flutter widget for rendering static html tags as Flutter widgets. (Will render over 70 different html tags!)
version: 1.0.0-pre.1
author: Matthew Whitaker <sub6resources@gmail.com>
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>=0.7.3-pre.38'

dependencies:
  html: ^0.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

