name: flutter_html
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.5

  # Plugin for parsing css
  csslib: ^1.0.2

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.19.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  meta: ^1.15.0
  melos: ^6.3.2

screenshots:
  - description: 'An example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot1.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot2.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot3.png
  - description: 'Another example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_readme_screenshot.png

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - css
  - widgets
  - layout
