name: flutter_matrix_html
description: A Flutter widget for rendering static matrix html tags as Flutter widgets. (Will render over 70 different html tags!)
version: 0.1.12
homepage: https://github.com/Sorunome/flutter_matrix_html

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=0.5.0'

dependencies:
  html: ^0.14.0
  flutter:
    sdk: flutter
  cached_network_image: any
  matrix_link_text: any
  flutter_math: ^0.2.0+2
  flutter_highlight: ^0.6.0
  isolate: ^2.0.3
  highlight: ^0.6.0
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
