name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 2.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  # Plugin for parsing html
  html: '>=0.15.0 <1.0.0'

  # Plugin for parsing css
  csslib: '>=0.17.0 <1.0.0'

  # Plugin for firstWhereOrNull extension on lists
  collection: '>=1.15.0 <2.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
