name: flutter_html_svg
description: This extension package allows the <svg> tag and svg-based img sources to be rendered using the flutter_html package
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: ^3.0.0
  flutter_svg: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  meta: ^1.15.0

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - css
  - svg
  - images
